package com.xmu.oomall.mapper;

import com.xmu.oomall.model.po.BrandPo;
import com.xmu.oomall.model.po.BrandPoExample;
import java.util.List;

public interface BrandPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated
     */
    int insert(BrandPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated
     */
    int insertSelective(BrandPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated
     */
    List<BrandPo> selectByExampleWithBLOBs(BrandPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated
     */
    List<BrandPo> selectByExample(BrandPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated
     */
    BrandPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BrandPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(BrandPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BrandPo record);
}