package com.xmu.oomall.model.po;

import java.time.LocalDateTime;

public class CouponPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.coupon_sn
     *
     * @mbg.generated
     */
    private String couponSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.avtivity_id
     *
     * @mbg.generated
     */
    private Integer avtivityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.begin_time
     *
     * @mbg.generated
     */
    private LocalDateTime beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon.state
     *
     * @mbg.generated
     */
    private Short state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.id
     *
     * @return the value of coupon.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.id
     *
     * @param id the value for coupon.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.coupon_sn
     *
     * @return the value of coupon.coupon_sn
     *
     * @mbg.generated
     */
    public String getCouponSn() {
        return couponSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.coupon_sn
     *
     * @param couponSn the value for coupon.coupon_sn
     *
     * @mbg.generated
     */
    public void setCouponSn(String couponSn) {
        this.couponSn = couponSn == null ? null : couponSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.name
     *
     * @return the value of coupon.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.name
     *
     * @param name the value for coupon.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.customer_id
     *
     * @return the value of coupon.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.customer_id
     *
     * @param customerId the value for coupon.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.avtivity_id
     *
     * @return the value of coupon.avtivity_id
     *
     * @mbg.generated
     */
    public Integer getAvtivityId() {
        return avtivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.avtivity_id
     *
     * @param avtivityId the value for coupon.avtivity_id
     *
     * @mbg.generated
     */
    public void setAvtivityId(Integer avtivityId) {
        this.avtivityId = avtivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.begin_time
     *
     * @return the value of coupon.begin_time
     *
     * @mbg.generated
     */
    public LocalDateTime getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.begin_time
     *
     * @param beginTime the value for coupon.begin_time
     *
     * @mbg.generated
     */
    public void setBeginTime(LocalDateTime beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.end_time
     *
     * @return the value of coupon.end_time
     *
     * @mbg.generated
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.end_time
     *
     * @param endTime the value for coupon.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon.state
     *
     * @return the value of coupon.state
     *
     * @mbg.generated
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon.state
     *
     * @param state the value for coupon.state
     *
     * @mbg.generated
     */
    public void setState(Short state) {
        this.state = state;
    }
}