package com.xmu.oomall.model.po;

import java.time.LocalDate;

public class FlashSalePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flash_sale.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flash_sale.falsh_date
     *
     * @mbg.generated
     */
    private LocalDate falshDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flash_sale.time_seg_id
     *
     * @mbg.generated
     */
    private Integer timeSegId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flash_sale.id
     *
     * @return the value of flash_sale.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flash_sale.id
     *
     * @param id the value for flash_sale.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flash_sale.falsh_date
     *
     * @return the value of flash_sale.falsh_date
     *
     * @mbg.generated
     */
    public LocalDate getFalshDate() {
        return falshDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flash_sale.falsh_date
     *
     * @param falshDate the value for flash_sale.falsh_date
     *
     * @mbg.generated
     */
    public void setFalshDate(LocalDate falshDate) {
        this.falshDate = falshDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flash_sale.time_seg_id
     *
     * @return the value of flash_sale.time_seg_id
     *
     * @mbg.generated
     */
    public Integer getTimeSegId() {
        return timeSegId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flash_sale.time_seg_id
     *
     * @param timeSegId the value for flash_sale.time_seg_id
     *
     * @mbg.generated
     */
    public void setTimeSegId(Integer timeSegId) {
        this.timeSegId = timeSegId;
    }
}