package com.xmu.oomall.model.po;

public class SPUPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu.brand_id
     *
     * @mbg.generated
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu.freight_id
     *
     * @mbg.generated
     */
    private Integer freightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu.goods_sn
     *
     * @mbg.generated
     */
    private String goodsSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu.image_url
     *
     * @mbg.generated
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu.state
     *
     * @mbg.generated
     */
    private Short state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu.disabled
     *
     * @mbg.generated
     */
    private Byte disabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu.id
     *
     * @return the value of goods_spu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu.id
     *
     * @param id the value for goods_spu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu.name
     *
     * @return the value of goods_spu.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu.name
     *
     * @param name the value for goods_spu.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu.brand_id
     *
     * @return the value of goods_spu.brand_id
     *
     * @mbg.generated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu.brand_id
     *
     * @param brandId the value for goods_spu.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu.category_id
     *
     * @return the value of goods_spu.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu.category_id
     *
     * @param categoryId the value for goods_spu.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu.freight_id
     *
     * @return the value of goods_spu.freight_id
     *
     * @mbg.generated
     */
    public Integer getFreightId() {
        return freightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu.freight_id
     *
     * @param freightId the value for goods_spu.freight_id
     *
     * @mbg.generated
     */
    public void setFreightId(Integer freightId) {
        this.freightId = freightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu.shop_id
     *
     * @return the value of goods_spu.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu.shop_id
     *
     * @param shopId the value for goods_spu.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu.goods_sn
     *
     * @return the value of goods_spu.goods_sn
     *
     * @mbg.generated
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu.goods_sn
     *
     * @param goodsSn the value for goods_spu.goods_sn
     *
     * @mbg.generated
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu.image_url
     *
     * @return the value of goods_spu.image_url
     *
     * @mbg.generated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu.image_url
     *
     * @param imageUrl the value for goods_spu.image_url
     *
     * @mbg.generated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu.state
     *
     * @return the value of goods_spu.state
     *
     * @mbg.generated
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu.state
     *
     * @param state the value for goods_spu.state
     *
     * @mbg.generated
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu.disabled
     *
     * @return the value of goods_spu.disabled
     *
     * @mbg.generated
     */
    public Byte getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu.disabled
     *
     * @param disabled the value for goods_spu.disabled
     *
     * @mbg.generated
     */
    public void setDisabled(Byte disabled) {
        this.disabled = disabled;
    }
}