package cn.edu.xmu.ooad.mapper;

import cn.edu.xmu.ooad.model.po.GrouponActivityPo;
import cn.edu.xmu.ooad.model.po.GrouponActivityPoExample;
import java.util.List;

public interface GrouponActivityPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_groupon_activity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_groupon_activity
     *
     * @mbg.generated
     */
    int insert(GrouponActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_groupon_activity
     *
     * @mbg.generated
     */
    int insertSelective(GrouponActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_groupon_activity
     *
     * @mbg.generated
     */
    List<GrouponActivityPo> selectByExample(GrouponActivityPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_groupon_activity
     *
     * @mbg.generated
     */
    GrouponActivityPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_groupon_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GrouponActivityPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_groupon_activity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GrouponActivityPo record);
}