package cn.edu.xmu.flashsale.model.po;

import java.time.LocalDateTime;

public class FlashSalePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flash_sale.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flash_sale.flash_date
     *
     * @mbg.generated
     */
    private LocalDateTime flashDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flash_sale.time_seg_id
     *
     * @mbg.generated
     */
    private Long timeSegId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flash_sale.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flash_sale.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flash_sale.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flash_sale.id
     *
     * @return the value of flash_sale.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flash_sale.id
     *
     * @param id the value for flash_sale.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flash_sale.flash_date
     *
     * @return the value of flash_sale.flash_date
     *
     * @mbg.generated
     */
    public LocalDateTime getFlashDate() {
        return flashDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flash_sale.flash_date
     *
     * @param flashDate the value for flash_sale.flash_date
     *
     * @mbg.generated
     */
    public void setFlashDate(LocalDateTime flashDate) {
        this.flashDate = flashDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flash_sale.time_seg_id
     *
     * @return the value of flash_sale.time_seg_id
     *
     * @mbg.generated
     */
    public Long getTimeSegId() {
        return timeSegId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flash_sale.time_seg_id
     *
     * @param timeSegId the value for flash_sale.time_seg_id
     *
     * @mbg.generated
     */
    public void setTimeSegId(Long timeSegId) {
        this.timeSegId = timeSegId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flash_sale.gmt_create
     *
     * @return the value of flash_sale.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flash_sale.gmt_create
     *
     * @param gmtCreate the value for flash_sale.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flash_sale.gmt_modified
     *
     * @return the value of flash_sale.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flash_sale.gmt_modified
     *
     * @param gmtModified the value for flash_sale.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flash_sale.state
     *
     * @return the value of flash_sale.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flash_sale.state
     *
     * @param state the value for flash_sale.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }
}