package cn.edu.xmu.ooad.model.po;

import java.time.LocalDateTime;

public class CouponPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_coupon.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_coupon.coupon_sn
     *
     * @mbg.generated
     */
    private String couponSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_coupon.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_coupon.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_coupon.activity_id
     *
     * @mbg.generated
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_coupon.begin_time
     *
     * @mbg.generated
     */
    private LocalDateTime beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_coupon.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_coupon.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_coupon.id
     *
     * @return the value of good_coupon.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_coupon.id
     *
     * @param id the value for good_coupon.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_coupon.coupon_sn
     *
     * @return the value of good_coupon.coupon_sn
     *
     * @mbg.generated
     */
    public String getCouponSn() {
        return couponSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_coupon.coupon_sn
     *
     * @param couponSn the value for good_coupon.coupon_sn
     *
     * @mbg.generated
     */
    public void setCouponSn(String couponSn) {
        this.couponSn = couponSn == null ? null : couponSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_coupon.name
     *
     * @return the value of good_coupon.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_coupon.name
     *
     * @param name the value for good_coupon.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_coupon.customer_id
     *
     * @return the value of good_coupon.customer_id
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_coupon.customer_id
     *
     * @param customerId the value for good_coupon.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_coupon.activity_id
     *
     * @return the value of good_coupon.activity_id
     *
     * @mbg.generated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_coupon.activity_id
     *
     * @param activityId the value for good_coupon.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_coupon.begin_time
     *
     * @return the value of good_coupon.begin_time
     *
     * @mbg.generated
     */
    public LocalDateTime getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_coupon.begin_time
     *
     * @param beginTime the value for good_coupon.begin_time
     *
     * @mbg.generated
     */
    public void setBeginTime(LocalDateTime beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_coupon.end_time
     *
     * @return the value of good_coupon.end_time
     *
     * @mbg.generated
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_coupon.end_time
     *
     * @param endTime the value for good_coupon.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_coupon.state
     *
     * @return the value of good_coupon.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_coupon.state
     *
     * @param state the value for good_coupon.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }
}