package cn.edu.xmu.ooad.model.po;

import java.time.LocalDateTime;

public class FlashSalePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_flash_sale.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_flash_sale.flash_date
     *
     * @mbg.generated
     */
    private LocalDateTime flashDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_flash_sale.time_seg_id
     *
     * @mbg.generated
     */
    private Long timeSegId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_flash_sale.id
     *
     * @return the value of good_flash_sale.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_flash_sale.id
     *
     * @param id the value for good_flash_sale.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_flash_sale.flash_date
     *
     * @return the value of good_flash_sale.flash_date
     *
     * @mbg.generated
     */
    public LocalDateTime getFlashDate() {
        return flashDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_flash_sale.flash_date
     *
     * @param flashDate the value for good_flash_sale.flash_date
     *
     * @mbg.generated
     */
    public void setFlashDate(LocalDateTime flashDate) {
        this.flashDate = flashDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_flash_sale.time_seg_id
     *
     * @return the value of good_flash_sale.time_seg_id
     *
     * @mbg.generated
     */
    public Long getTimeSegId() {
        return timeSegId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_flash_sale.time_seg_id
     *
     * @param timeSegId the value for good_flash_sale.time_seg_id
     *
     * @mbg.generated
     */
    public void setTimeSegId(Long timeSegId) {
        this.timeSegId = timeSegId;
    }
}