package cn.edu.xmu.ooad.model.po;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class FloatPricePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_float_price.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_float_price.goods_sku_id
     *
     * @mbg.generated
     */
    private Long goodsSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_float_price.activity_price
     *
     * @mbg.generated
     */
    private BigDecimal activityPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_float_price.begin_time
     *
     * @mbg.generated
     */
    private LocalDateTime beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_float_price.end_time
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_float_price.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_float_price.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_float_price.invalid_by
     *
     * @mbg.generated
     */
    private Long invalidBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_float_price.valid
     *
     * @mbg.generated
     */
    private Byte valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_float_price.id
     *
     * @return the value of good_float_price.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_float_price.id
     *
     * @param id the value for good_float_price.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_float_price.goods_sku_id
     *
     * @return the value of good_float_price.goods_sku_id
     *
     * @mbg.generated
     */
    public Long getGoodsSkuId() {
        return goodsSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_float_price.goods_sku_id
     *
     * @param goodsSkuId the value for good_float_price.goods_sku_id
     *
     * @mbg.generated
     */
    public void setGoodsSkuId(Long goodsSkuId) {
        this.goodsSkuId = goodsSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_float_price.activity_price
     *
     * @return the value of good_float_price.activity_price
     *
     * @mbg.generated
     */
    public BigDecimal getActivityPrice() {
        return activityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_float_price.activity_price
     *
     * @param activityPrice the value for good_float_price.activity_price
     *
     * @mbg.generated
     */
    public void setActivityPrice(BigDecimal activityPrice) {
        this.activityPrice = activityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_float_price.begin_time
     *
     * @return the value of good_float_price.begin_time
     *
     * @mbg.generated
     */
    public LocalDateTime getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_float_price.begin_time
     *
     * @param beginTime the value for good_float_price.begin_time
     *
     * @mbg.generated
     */
    public void setBeginTime(LocalDateTime beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_float_price.end_time
     *
     * @return the value of good_float_price.end_time
     *
     * @mbg.generated
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_float_price.end_time
     *
     * @param endTime the value for good_float_price.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_float_price.quantity
     *
     * @return the value of good_float_price.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_float_price.quantity
     *
     * @param quantity the value for good_float_price.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_float_price.created_by
     *
     * @return the value of good_float_price.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_float_price.created_by
     *
     * @param createdBy the value for good_float_price.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_float_price.invalid_by
     *
     * @return the value of good_float_price.invalid_by
     *
     * @mbg.generated
     */
    public Long getInvalidBy() {
        return invalidBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_float_price.invalid_by
     *
     * @param invalidBy the value for good_float_price.invalid_by
     *
     * @mbg.generated
     */
    public void setInvalidBy(Long invalidBy) {
        this.invalidBy = invalidBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_float_price.valid
     *
     * @return the value of good_float_price.valid
     *
     * @mbg.generated
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_float_price.valid
     *
     * @param valid the value for good_float_price.valid
     *
     * @mbg.generated
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }
}