package cn.edu.xmu.ooad.model.po;

public class ShopPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_shop.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_shop.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_shop.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_shop.id
     *
     * @return the value of good_shop.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_shop.id
     *
     * @param id the value for good_shop.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_shop.name
     *
     * @return the value of good_shop.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_shop.name
     *
     * @param name the value for good_shop.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_shop.state
     *
     * @return the value of good_shop.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_shop.state
     *
     * @param state the value for good_shop.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }
}