package cn.edu.xmu.ooad.model.po;

public class SKUPoWithBLOBs extends SKUPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sku.configration
     *
     * @mbg.generated
     */
    private String configration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sku.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sku.configration
     *
     * @return the value of goods_sku.configration
     *
     * @mbg.generated
     */
    public String getConfigration() {
        return configration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sku.configration
     *
     * @param configration the value for goods_sku.configration
     *
     * @mbg.generated
     */
    public void setConfigration(String configration) {
        this.configration = configration == null ? null : configration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sku.detail
     *
     * @return the value of goods_sku.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sku.detail
     *
     * @param detail the value for goods_sku.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}