package cn.edu.xmu.ooad.model.po;

public class SPUPoWithBLOBs extends SPUPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_spu.spec
     *
     * @mbg.generated
     */
    private String spec;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu.detail
     *
     * @return the value of goods_spu.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu.detail
     *
     * @param detail the value for goods_spu.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_spu.spec
     *
     * @return the value of goods_spu.spec
     *
     * @mbg.generated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_spu.spec
     *
     * @param spec the value for goods_spu.spec
     *
     * @mbg.generated
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }
}