package cn.edu.xmu.ooad.model.po;

public class SPUPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_goods_spu.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_goods_spu.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_goods_spu.brand_id
     *
     * @mbg.generated
     */
    private Long brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_goods_spu.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_goods_spu.freight_id
     *
     * @mbg.generated
     */
    private Long freightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_goods_spu.shop_id
     *
     * @mbg.generated
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_goods_spu.goods_sn
     *
     * @mbg.generated
     */
    private String goodsSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_goods_spu.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_goods_spu.image_url
     *
     * @mbg.generated
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_goods_spu.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_goods_spu.spec
     *
     * @mbg.generated
     */
    private String spec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_goods_spu.disabled
     *
     * @mbg.generated
     */
    private Byte disabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_goods_spu.id
     *
     * @return the value of good_goods_spu.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_goods_spu.id
     *
     * @param id the value for good_goods_spu.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_goods_spu.name
     *
     * @return the value of good_goods_spu.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_goods_spu.name
     *
     * @param name the value for good_goods_spu.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_goods_spu.brand_id
     *
     * @return the value of good_goods_spu.brand_id
     *
     * @mbg.generated
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_goods_spu.brand_id
     *
     * @param brandId the value for good_goods_spu.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_goods_spu.category_id
     *
     * @return the value of good_goods_spu.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_goods_spu.category_id
     *
     * @param categoryId the value for good_goods_spu.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_goods_spu.freight_id
     *
     * @return the value of good_goods_spu.freight_id
     *
     * @mbg.generated
     */
    public Long getFreightId() {
        return freightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_goods_spu.freight_id
     *
     * @param freightId the value for good_goods_spu.freight_id
     *
     * @mbg.generated
     */
    public void setFreightId(Long freightId) {
        this.freightId = freightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_goods_spu.shop_id
     *
     * @return the value of good_goods_spu.shop_id
     *
     * @mbg.generated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_goods_spu.shop_id
     *
     * @param shopId the value for good_goods_spu.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_goods_spu.goods_sn
     *
     * @return the value of good_goods_spu.goods_sn
     *
     * @mbg.generated
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_goods_spu.goods_sn
     *
     * @param goodsSn the value for good_goods_spu.goods_sn
     *
     * @mbg.generated
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_goods_spu.detail
     *
     * @return the value of good_goods_spu.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_goods_spu.detail
     *
     * @param detail the value for good_goods_spu.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_goods_spu.image_url
     *
     * @return the value of good_goods_spu.image_url
     *
     * @mbg.generated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_goods_spu.image_url
     *
     * @param imageUrl the value for good_goods_spu.image_url
     *
     * @mbg.generated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_goods_spu.state
     *
     * @return the value of good_goods_spu.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_goods_spu.state
     *
     * @param state the value for good_goods_spu.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_goods_spu.spec
     *
     * @return the value of good_goods_spu.spec
     *
     * @mbg.generated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_goods_spu.spec
     *
     * @param spec the value for good_goods_spu.spec
     *
     * @mbg.generated
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_goods_spu.disabled
     *
     * @return the value of good_goods_spu.disabled
     *
     * @mbg.generated
     */
    public Byte getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_goods_spu.disabled
     *
     * @param disabled the value for good_goods_spu.disabled
     *
     * @mbg.generated
     */
    public void setDisabled(Byte disabled) {
        this.disabled = disabled;
    }
}