package cn.edu.xmu.flashsale.mapper;

import cn.edu.xmu.flashsale.model.po.FlashSaleItemPo;
import cn.edu.xmu.flashsale.model.po.FlashSaleItemPoExample;
import java.util.List;

public interface FlashSaleItemPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale_item
     *
     * @mbg.generated
     */
    int insert(FlashSaleItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale_item
     *
     * @mbg.generated
     */
    int insertSelective(FlashSaleItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale_item
     *
     * @mbg.generated
     */
    List<FlashSaleItemPo> selectByExample(FlashSaleItemPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale_item
     *
     * @mbg.generated
     */
    FlashSaleItemPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlashSaleItemPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flash_sale_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlashSaleItemPo record);
}