package cn.edu.xmu.activity.mapper;

import cn.edu.xmu.activity.model.po.CouponSKUPo;
import cn.edu.xmu.activity.model.po.CouponSKUPoExample;
import java.util.List;

public interface CouponSKUPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_sku
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_sku
     *
     * @mbg.generated
     */
    int insert(CouponSKUPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_sku
     *
     * @mbg.generated
     */
    int insertSelective(CouponSKUPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_sku
     *
     * @mbg.generated
     */
    List<CouponSKUPo> selectByExample(CouponSKUPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_sku
     *
     * @mbg.generated
     */
    CouponSKUPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CouponSKUPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CouponSKUPo record);
}